---
openapi: 3.0.1
info:
  title: CYR3CON_MALWARE

security:
- userId: []
  apiKey: []
paths:
  "/v1/account/login":
    post:
      tags:
      - MALWARE
      description: authorizes user and returns apiKey required in all other endpoints
      operationId: Login
      parameters:
      - name: userId
        in: header
        description: User ID for the cyr3con
        required: true
        schema:
          type: string
      - name: password
        in: header
        description: Password for the cyr3con.
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LoginResponse"
      security: []
  "/v1/account/reset-password":
    post:
      tags:
      - MALWARE
      operationId: Reset Password
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/InitResetPasswordRequestDto"
        required: true
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountActionStatus"
      security: []
  "/v1/account/change-password":
    post:
      tags:
      - MALWARE
      operationId: Change Password
      parameters:
      - name: oldPassword
        in: header
        required: true
        schema:
          type: string
      - name: newPassword
        in: header
        required: true
        schema:
          type: string
      - name: confirmPassword
        in: header
        required: true
        schema:
          type: string
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/AccountActionStatus"
      security: []
  "/v1/account/logout":
    post:
      tags:
      - MALWARE
      operationId: Logout
      parameters:
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/LogoutStatus"
      security: []
  "/v1/data-leaks":
    get:
      tags:
      - MALWARE
      operationId: Data Leaks
      parameters:
      - name: fileName
        in: query
        description: Returns the results with matching file name.
        required: false
        schema:
          type: string
      - name: fileType
        in: query
        description: Returns the results with matching file type.
        required: false
        schema:
          type: string
      - name: content
        in: query
        description: Used for content search over the content passed.
        required: false
        schema:
          type: string
      - name: phraseSearch
        in: query
        description: phrase that needs to be searched in the text.
        required: false
        schema:
          type: array
          items:
            type: string
      - name: enableFuzzy
        in: query
        description: If set to true, it will do the fuzzy search for the content being
          passed.
        required: false
        schema:
          type: boolean
      - name: start
        in: query
        description: Start record for results to be retrieved.
        required: true
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: limit
        in: query
        description: Number of records to be retrieved.
        required: false
        schema:
          maximum: 5000
          minimum: 1
          type: integer
          default: 10
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GenericResponseDataLeaks"
      security: []
  "/v1/data-leaks/files":
    get:
      tags:
      - MALWARE
      operationId: downloadDataLeaks
      parameters:
      - name: fileName
        in: query
        description: Returns the results with matching file name.
        required: false
        schema:
          type: string
      - name: fileType
        in: query
        description: Returns the results with matching file type.
        required: false
        schema:
          type: string
      - name: content
        in: query
        description: Used for content search over the content passed.
        required: false
        schema:
          type: string
      - name: phraseSearch
        in: query
        description: phrase that needs to be searched in the text.
        required: false
        schema:
          type: array
          items:
            type: string
      - name: enableFuzzy
        in: query
        description: If set to true, it will do the fuzzy search for the content being
          passed.
        required: false
        schema:
          type: boolean
      - name: start
        in: query
        description: Start record for results to be retrieved.
        required: true
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: limit
        in: query
        description: Number of records to be retrieved.
        required: false
        schema:
          maximum: 5000
          minimum: 1
          type: integer
          default: 10
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: byte
      security: []
  "/v1/dumps-s3/files":
    get:
      tags:
      - MALWARE
      description: To download malware files
      operationId: Dumps S3 Download
      parameters:
      - name: sha256Hash
        in: query
        description: Returns unique version of record/file attached with this SHA256
          key
        required: false
        schema:
          type: string
      - name: md5Hash
        in: query
        description: Returns unique version of record/file attached with this md5
          key
        required: false
        schema:
          type: string
      - name: fileName
        in: query
        description: Returns the results with matching file name.
        required: false
        schema:
          type: string
      - name: fileType
        in: query
        description: Returns the results with matching file type.
        required: false
        schema:
          type: string
      - name: start
        in: query
        description: Start record for results to be retrieved.
        required: true
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: limit
        in: query
        description: Number of records to be retrieved.
        required: false
        schema:
          maximum: 5000
          minimum: 1
          type: integer
          default: 10
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  format: byte
      security: []
  "/v1/dumps-s3/mappings":
    get:
      tags:
      - MALWARE
      description: To get a list of dumps S3 mapping
      operationId: Dumps S3 Mappings
      parameters:
      - name: sha256Hash
        in: query
        description: Returns unique version of record/file attached with this SHA256
          key
        required: false
        schema:
          type: string
      - name: md5Hash
        in: query
        description: Returns unique version of record/file attached with this md5
          key
        required: false
        schema:
          type: string
      - name: fileName
        in: query
        description: Returns the results with matching file name.
        required: false
        schema:
          type: string
      - name: fileType
        in: query
        description: Returns the results with matching file type.
        required: false
        schema:
          type: string
      - name: start
        in: query
        description: Start record for results to be retrieved.
        required: true
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: limit
        in: query
        description: Number of records to be retrieved.
        required: false
        schema:
          maximum: 5000
          minimum: 1
          type: integer
          default: 10
      - name: userId
        in: header
        required: true
        schema:
          type: string
      - name: apiKey
        in: header
        required: true
        schema:
          type: uuid
      responses:
        '200':
          description: successful response
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GenericResponseCuckooReport"
      security: []
components:
  schemas:
    InitResetPasswordRequestDto:
      required:
      - userId
      type: object
      properties:
        userId:
          type: string
          format: string
    AccountActionStatus:
      type: object
      properties:
        message:
          type: string
          format: string
    LogoutStatus:
      type: object
      properties:
        message:
          type: string
          format: string
    LoginResponse:
      type: object
      properties:
        status:
          type: string
          format: string
          enum:
          - 100 CONTINUE
          - 101 SWITCHING_PROTOCOLS
          - 102 PROCESSING
          - 103 CHECKPOINT
          - 200 OK
          - 201 CREATED
          - 202 ACCEPTED
          - 203 NON_AUTHORITATIVE_INFORMATION
          - 204 NO_CONTENT
          - 205 RESET_CONTENT
          - 206 PARTIAL_CONTENT
          - 207 MULTI_STATUS
          - 208 ALREADY_REPORTED
          - 226 IM_USED
          - 300 MULTIPLE_CHOICES
          - 301 MOVED_PERMANENTLY
          - 302 FOUND
          - 302 MOVED_TEMPORARILY
          - 303 SEE_OTHER
          - 304 NOT_MODIFIED
          - 305 USE_PROXY
          - 307 TEMPORARY_REDIRECT
          - 308 PERMANENT_REDIRECT
          - 400 BAD_REQUEST
          - 401 UNAUTHORIZED
          - 402 PAYMENT_REQUIRED
          - 403 FORBIDDEN
          - 404 NOT_FOUND
          - 405 METHOD_NOT_ALLOWED
          - 406 NOT_ACCEPTABLE
          - 407 PROXY_AUTHENTICATION_REQUIRED
          - 408 REQUEST_TIMEOUT
          - 409 CONFLICT
          - 410 GONE
          - 411 LENGTH_REQUIRED
          - 412 PRECONDITION_FAILED
          - 413 PAYLOAD_TOO_LARGE
          - 413 REQUEST_ENTITY_TOO_LARGE
          - 414 URI_TOO_LONG
          - 414 REQUEST_URI_TOO_LONG
          - 415 UNSUPPORTED_MEDIA_TYPE
          - 416 REQUESTED_RANGE_NOT_SATISFIABLE
          - 417 EXPECTATION_FAILED
          - 418 I_AM_A_TEAPOT
          - 419 INSUFFICIENT_SPACE_ON_RESOURCE
          - 420 METHOD_FAILURE
          - 421 DESTINATION_LOCKED
          - 422 UNPROCESSABLE_ENTITY
          - 423 LOCKED
          - 424 FAILED_DEPENDENCY
          - 425 TOO_EARLY
          - 426 UPGRADE_REQUIRED
          - 428 PRECONDITION_REQUIRED
          - 429 TOO_MANY_REQUESTS
          - 431 REQUEST_HEADER_FIELDS_TOO_LARGE
          - 451 UNAVAILABLE_FOR_LEGAL_REASONS
          - 500 INTERNAL_SERVER_ERROR
          - 501 NOT_IMPLEMENTED
          - 502 BAD_GATEWAY
          - 503 SERVICE_UNAVAILABLE
          - 504 GATEWAY_TIMEOUT
          - 505 HTTP_VERSION_NOT_SUPPORTED
          - 506 VARIANT_ALSO_NEGOTIATES
          - 507 INSUFFICIENT_STORAGE
          - 508 LOOP_DETECTED
          - 509 BANDWIDTH_LIMIT_EXCEEDED
          - 510 NOT_EXTENDED
          - 511 NETWORK_AUTHENTICATION_REQUIRED
        userId:
          type: string
          format: string
        roles:
          type: array
          format: array
          items:
            type: string
        uiFeatures:
          type: array
          format: array
          items:
            type: string
        apiKey:
          type: string
          format: string(uuid)
        apiKeyCreatedOn:
          type: string
          format: string(date-time)
        apiKeyExpiresOn:
          type: string
          format: string(date-time)
        changePassword:
          type: string
          format: string
        message:
          type: string
          format: string
        twoFactor:
          type: boolean
          format: boolean
        lastActivityTime:
          type: string
          format: string(date-time)
        privacyPolicyAcceptanceRequired:
          type: boolean
          format: boolean
    CuckooReport:
      type: object
      properties:
        languageType:
          type: string
          description: Type of language. Mostly, text.
          format: 'string :: Type of language. Mostly, text.'
        sha256Hash:
          type: string
          description: sha256 hash for the file
          format: 'string :: sha256 hash for the file'
        fileExtension:
          type: string
          description: Extension of file
          format: 'string :: Extension of file'
        md5Hash:
          type: string
          format: string
        fileName:
          type: string
          description: Name of the file
          format: 'string :: Name of the file'
        createdDate:
          type: string
          description: Date when the file was created
          format: 'string(date) :: Date when the file was created'
        cveMentions:
          type: array
          description: List of cve mentions in file.
          format: 'array :: List of cve mentions in file.'
          items:
            type: string
            description: List of cve mentions in file.
        firstSeen:
          type: string
          format: string
        fileType:
          type: string
          format: string
        strings:
          type: array
          format: array
          items:
            type: string
        info:
          "$ref": "#/components/schemas/CuckooReportInfo"
        target:
          "$ref": "#/components/schemas/CuckooReportTarget"
        score:
          type: number
          format: number
    CuckooReportInfo:
      type: object
      properties:
        added:
          type: string
          format: string(date-time)
        started:
          type: string
          format: string(date-time)
        duration:
          type: integer
          format: integer(int32)
        owner:
          type: string
          format: string
        score:
          type: number
          format: number
        id:
          type: integer
          format: integer(int32)
        ended:
          type: string
          format: string(date-time)
        category:
          type: string
          format: string
        monitor:
          type: string
          format: string
        infoPackage:
          type: string
          format: string
        route:
          type: string
          format: string
        custom:
          type: string
          format: string
        platform:
          type: string
          format: string
        version:
          type: string
          format: string
        options:
          type: string
          format: string
        git:
          "$ref": "#/components/schemas/CuckooReportInfoGit"
        machine:
          "$ref": "#/components/schemas/CuckooReportInfoMachine"
    CuckooReportInfoGit:
      type: object
      properties:
        head:
          type: string
          format: string
        fetchHead:
          type: string
          format: string
    CuckooReportInfoMachine:
      type: object
      properties:
        status:
          type: string
          format: string
        name:
          type: string
          format: string
        label:
          type: string
          format: string
        manager:
          type: string
          format: string
        startedOn:
          type: string
          format: string
        shutdownOn:
          type: string
          format: string
    CuckooReportTarget:
      type: object
      properties:
        category:
          type: string
          format: string
        file:
          "$ref": "#/components/schemas/CuckooReportTargetFile"
    CuckooReportTargetFile:
      type: object
      properties:
        sha1:
          type: string
          format: string
        name:
          type: string
          format: string
        type:
          type: string
          format: string
        sha256:
          type: string
          format: string
        urls:
          type: array
          format: array
          items:
            type: string
        crc32:
          type: string
          format: string
        path:
          type: string
          format: string
        ssDeep:
          type: string
          format: string
        size:
          type: integer
          format: integer(int32)
        sha512:
          type: string
          format: string
        md5:
          type: string
          format: string
    GenericResponseCuckooReport:
      type: object
      properties:
        type:
          type: string
          format: string
        message:
          type: string
          format: string
        results:
          type: array
          format: array
          items:
            "$ref": "#/components/schemas/CuckooReport"
        count:
          type: integer
          format: integer(int64)
    DataLeaks:
      type: object
      properties:
        fileName:
          type: string
          format: string
        fileType:
          type: string
          format: string
        content:
          type: string
          format: string
        score:
          type: number
          format: number
        _score:
          type: number
          format: number
    GenericResponseDataLeaks:
      type: object
      properties:
        type:
          type: string
          format: string
        message:
          type: string
          format: string
        results:
          type: array
          format: array
          items:
            "$ref": "#/components/schemas/DataLeaks"
        count:
          type: integer
          format: integer(int64)
  securitySchemes:
    userId:
      type: apiKey
      description: "(Required)"
      name: userId
      in: header
    apiKey:
      type: apiKey
      description: "(Required)"
      name: apiKey
      in: header

